/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bloodbankmangment;

import java.awt.Color;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mesi
 */
public class Update_purch extends javax.swing.JFrame {

    /**
     * Creates new form Update
     */
    public Update_purch() {
        initComponents();
        setSize(1000,1000);
        getContentPane().setBackground(new Color(255,102,102));
        setTitle("UPDAT PURCHASER");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender = new javax.swing.JLabel();
        mobile = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        AGE = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        city = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        BloodGroup = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        search = new javax.swing.JButton();
        idd = new javax.swing.JTextField();
        genderr = new javax.swing.JTextField();
        bloodgroup = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rest = new javax.swing.JButton();
        close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        gender.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        gender.setText("Gender");
        getContentPane().add(gender);
        gender.setBounds(389, 204, 49, 19);

        mobile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(mobile);
        mobile.setBounds(124, 334, 230, 30);

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jLabel2.setText("Age");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(49, 269, 27, 19);

        AGE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(AGE);
        AGE.setBounds(128, 264, 226, 30);

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jLabel4.setText("City");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(420, 340, 26, 19);
        getContentPane().add(city);
        city.setBounds(480, 330, 230, 30);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jLabel1.setText("Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(49, 204, 43, 19);

        name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name);
        name.setBounds(124, 199, 230, 30);

        BloodGroup.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        BloodGroup.setText("BloodGroup");
        getContentPane().add(BloodGroup);
        BloodGroup.setBounds(380, 250, 85, 50);

        phone.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        phone.setText("Phone");
        getContentPane().add(phone);
        phone.setBounds(49, 344, 43, 19);

        update.setBackground(new java.awt.Color(204, 204, 204));
        update.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        update.setForeground(new java.awt.Color(102, 102, 102));
        update.setText("Update");
        update.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(166, 478, 96, 33);

        search.setBackground(new java.awt.Color(204, 204, 204));
        search.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        search.setForeground(new java.awt.Color(102, 102, 102));
        search.setText("Search");
        search.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search);
        search.setBounds(571, 89, 65, 28);
        getContentPane().add(idd);
        idd.setBounds(295, 94, 230, 22);

        genderr.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        genderr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderrActionPerformed(evt);
            }
        });
        getContentPane().add(genderr);
        genderr.setBounds(478, 199, 230, 30);
        getContentPane().add(bloodgroup);
        bloodgroup.setBounds(480, 260, 226, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 457, 775, 3);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(6, 143, 769, 27);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(0, 74, 775, 3);

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jLabel3.setText("ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(205, 95, 25, 19);

        jLabel5.setFont(new java.awt.Font("Manjari", 1, 30)); // NOI18N
        jLabel5.setText("Update Purchaser Record");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(239, 7, 400, 55);

        rest.setBackground(new java.awt.Color(204, 204, 204));
        rest.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        rest.setForeground(new java.awt.Color(102, 102, 102));
        rest.setText("Reset");
        rest.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        rest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restActionPerformed(evt);
            }
        });
        getContentPane().add(rest);
        rest.setBounds(351, 478, 63, 33);

        close.setBackground(new java.awt.Color(204, 204, 204));
        close.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        close.setForeground(new java.awt.Color(255, 51, 0));
        close.setText("close");
        close.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close);
        close.setBounds(510, 478, 100, 33);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:\
        String ID=idd.getText();
        String Name = name.getText();
        String Age = AGE.getText();
        String PHone = mobile.getText();
        String Gender = gender.getText();
        String bloodtype =bloodgroup.getText();
        String City = city.getText();
        try {
            String sql = "UPDATE purchaser SET name=?,Age=?,Phone=?,Gender=?,city=?,BloodGroup=? WHERE id =" +ID;
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/bloodbank", "root", "");
            Statement st = con.createStatement();
                  st.executeUpdate("UPDATE purchaser SET name='"+Name+"',Age='"+Age+"',Phone='"+PHone+"',Gender='"+Gender+"',BloodGroup='"+bloodtype+"',city='"+City+"' WHERE id ='" +ID+"'");
                    JOptionPane.showMessageDialog(this,"Update record");
                    setVisible(false);
                    new Update_purch().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Connectoin error");
        }

    }//GEN-LAST:event_updateActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
       String Id=idd.getText();
        try {
            // TODO add your handling code here:
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/bloodBank", "root", "");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from purchaser where id='"+Id+"'");
            if(rs.next()){
            name.setText(rs.getString(2));
            AGE.setText(rs.getString(3));
            mobile.setText(rs.getString(4));
            gender.setText(rs.getString(5));
           
            city.setText(rs.getString(7));
             bloodgroup.setText(rs.getString(6));
            idd.setEditable(false);
            }else{
                 JOptionPane.showMessageDialog(this,"no record");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Update_purch.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchActionPerformed

    private void restActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restActionPerformed
              // TODO add your handling code here:
        setVisible(false);
        new Update_purch().setVisible(true);
    }//GEN-LAST:event_restActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_closeActionPerformed

    private void genderrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update_purch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update_purch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update_purch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update_purch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update_purch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AGE;
    private javax.swing.JLabel BloodGroup;
    private javax.swing.JTextField bloodgroup;
    private javax.swing.JTextField city;
    private javax.swing.JButton close;
    private javax.swing.JLabel gender;
    private javax.swing.JTextField genderr;
    private javax.swing.JTextField idd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField mobile;
    private javax.swing.JTextField name;
    private javax.swing.JLabel phone;
    private javax.swing.JButton rest;
    private javax.swing.JButton search;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

    private Color Color(int i, int i0, int i1) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    void setvisible(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
